### ISSUE TITLE
Como contribuir com sugestoes e correções?

### ISSUE THREAD

**Issue by dersonbsb2022** [ocarolino/SalamandraRadio#2]
Boa tarde, nunca utilizei o github e desculpe antecipadamente se estiver comentendo alguma gafe.

achei interessante o seu projeto, sou entusiasta do mundo de radio e vi comentando sobre o seu projeto e resolvi testa-lo.

Minhas duvidas e sugestoes primeiramente.

Vi alguem abrindo uma correcao em inglês, nao sei se é possivel, mas nao seria interessante ter um em ingles e outro em portugues? Pelo que vejo nos grupos que participo, a maioria teria grande dificuldade em escrever em ingles e ler tambem. Facilitaria a adesao se puder ser em portugues tambem.

Encontrei um bug e ja tenho uma sugestao, onde eu posto as sugestoes de melhorias?

obrigado pela iniciativa e estou disposto a ajudar com o crescimento do software, que é extremamente leve em comparaçao aos concorrentes e tem um grande potencial.

Desculpe por qualquer coisa, se quiser apagar isso que escrevi, vou entender.

Abs.

**Comment by ocarolino** [comment]
Boa tarde, pode postar em português por aqui mesmo, não tem problema. Esta semana mesmo abrirei um grupo no Facebook para concentrar as questões e conversas mais simples.

Sobre o bug e a sugestão, pode responder aqui mesmo como comentário. Só seja o mais detalhado possível, ok, para que eu possa reproduzir o bug na minha máquina e achar a causa. Ex: Cliquei em botão tal, depois fiz tal coisa e aconteceu x.

Agradeço pelo apoio.

**Comment by dersonbsb2022** [comment]
Fiz um video do primeiro bug que eu achei.

Configuracao: Windows 10 PRO + voicemeeter Banana.

Nao consigo trocar a saida de audio principal, mesmo que eu altere, o player continua tocando na mesma saida.

Inclusive, eu alterando no windows a saida padrao para outra, ele continua saindo na mesma.

https://youtu.be/1JVYvcMYL8g

Obs: Outros sistemas como Radioboss e Zara Radio, estao ok no mesmo computador.


Uma sugestao que gostaria que fosse implementada, é a de uma playlist auxiliar para que possamos trabalhar com edicão de novos blocos etc, enquanto o player está tocando a principal. Tentei abrir outra instancia para editar em um e tocar em outro, mas no Windows 10 pelo menos nao foi possivel, voltava sempre pro mesmo aplicativo ja em execução.
Entao ao ligar o player, o sistema fica escravo do processo e nao consigo adicionar novos blocos, comerciais etc.

Outra Sugestao que eu tenho era dividir a parte de eventos e colocar o log, sendo possivel a visualização das ultimas musicas, ate para que possamos desanunciar as ultimas musicas tocadas.

Gostei do sistema, achei ele super leve em comparação aos demais, e se possivel colocar a playlist auxiliar eu ja vou deixar ele tocando o dia todo. Tudo bem que posso fazer o arquivo m3u em outro aplicativo e abrir nele, mas como a gente está falando de automação, acho valido o sistema fazer tudo logo e que possamos instalar menos aplicativos no computador que vai ao ar.

Abs.

**Comment by ocarolino** [comment]
Bom dia,

Essa questão da placa não é bug, você tem que configurar a placa e fechar e abrir o programa de novo. Isso pode ser alterado no futuro para ficar mais fácil pra usuários que desejam alterar sem precisar reabrir o Salamandra, mas no momento é um comportamento intencional mesmo.

Mudar a saída principal também não vai afetar o programa. A saída padrão só vai ser utilizada ao abrir pela primeira vez ou caso o dispositivo de saída definido no Salamandra seja desativado/retirado do computador. Isso é para evitar o caso do usuário mudar sua saída padrão no Windows, mas não desejar que isso aconteça no programa. Ou até mesmo uma mudança acidental, algumas versões do Windows podem mudar o dispositivo padrão automaticamente, quando retira um dispositivo USB, por exemplo.

As sugestões para a playlist auxiliar e o histórico das últimas faixas tocadas é algo que agregarei sim aos planos futuros =)

Sobre abrir outra instância, tem uma configuração "Permitir a abertura de múltiplas instâncias", na aba Geral em Configurações. Verifique se ela está ativada, se estiver e mesmo assim não conseguir abrir, então é um bug mesmo.

Abraços!

**Comment by dersonbsb2022** [comment]
Ah tranquilo entao. Não é o comportamento dos demais, por isso achei "estranho". Mas entendo sua preocupaçao.

Hoje estou na rua o dia todo, chegando em casa vou tirar duvida sobre os outros pontos e te retorno.

No mais, no que eu puder ajudar, estou a disposição. =)

Abraços.
